### ISSUE TITLE
Error to build PDF file

### ISSUE THREAD

**Issue by hellangleZ** [AI4Finance-Foundation/FinRobot#19]
Traceback (most recent call last):
  File "/aml/FinRobot/finrobot/functional/reportlab.py", line 185, in build_annual_report
    name = YFinanceUtils.get_stock_info(ticker_symbol)["shortName"]
  File "/aml/FinRobot/finrobot/data_source/yfinance_utils.py", line 15, in wrapper
    return func(ticker, *args, **kwargs)
  File "/aml/FinRobot/finrobot/data_source/yfinance_utils.py", line 44, in get_stock_info
    stock_info = ticker.info
  File "/root/miniconda3/lib/python3.10/site-packages/yfinance/ticker.py", line 153, in info
    return self.get_info()
  File "/root/miniconda3/lib/python3.10/site-packages/yfinance/base.py", line 223, in get_info
    data = self._quote.info
  File "/root/miniconda3/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 561, in info
    self._fetch_complementary(self.proxy)
  File "/root/miniconda3/lib/python3.10/site-packages/yfinance/scrapers/quote.py", line 721, in _fetch_complementary
    json_data = json.loads(json_str)
  File "/root/miniconda3/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda3/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/miniconda3/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by hellangleZ** [comment]
![image](https://github.com/AI4Finance-Foundation/FinRobot/assets/15274284/869e2ad6-0ef8-4b83-bff2-01822b84186f)

There are still 4 files, but due to this issue, could not create PDF, and the error is early to pop in other ipynb project


![image](https://github.com/AI4Finance-Foundation/FinRobot/assets/15274284/2ef4e96d-a87a-4220-853a-98a8c00a2d55)

**Comment by SijiaLi0807** [comment]
I can't build pdf as well.
